### ISSUE TITLE
How do I disable some convertions?

### ISSUE THREAD

**Issue by ghost** [taiyuuki/character-conversion#1]
I'd need just the `characterConversion.arrow` to be enabled, and I wanted to disable all the rest, how do I do that?

**Comment by taiyuuki** [comment]
Currently unable to disable.
I didn't originally plan to maintain this extension, I suggest you use fonts that contain ligatures. But this issue can be resolved in the next update. By leaving blank the configuration that needs to be disabled in the settings.

**Comment by ghost** [comment]
@taiyuuki thank you for the response, I really like your extension, but no worries with that. And thank you for the suggestion.
